---
title: "4-1 函数"
subtitle: ''
author: "Humoon"
date: "`r Sys.Date()`"
output:
  html_document: 
    code_download: true
    fig_caption: yes
    theme: united
    highlight: haddock
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  rticles::ctex:
    df_print: default
    fig_caption: yes
    number_sections: false
  word_document:
    fig_caption: yes
    toc: yes
    toc_depth: 3
    reference_docx: 
  pdf_document: 
    toc: yes
    toc_depth: 2
    latex_engine: xelatex
documentclass: ctexart
classoption: hyperref,
---

```{css, echo=FALSE}
/* 除了直接在Rmd中写css，还可以在 yaml 头部加入 css:"style.css" 来使用外部css文件 */
  
  
/* 全局 */

body {
    font-size: 16px;
    color: #333333;
    font-family: sans-serif, 'Segoe UI', Tahoma, Geneva, Verdana, SimSun;
}

p,
blockquote,
ul,
ol,
dl,
table {
    margin: 0.8em 0;
}


/* 多级标题 */

h1 {
    font-size: 32px;
    margin-top: 1em;
    margin-bottom: 1em;
    color: red;
    font-weight: bold;
}

h2 {
    font-size: 28px;
    margin-top: 1em;
    margin-bottom: 1em;
    color: purple;
    font-weight: bold;
}

h3 {
    color: darkslateblue;
    font-size: 24px;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    font-weight: bold;
}

h4 {
    font-size: 20px;
    font-weight: bold;
}

h1.title,
h3.subtitle,
h4.author,
h4.date {
    margin-top: 0.5em;
    margin-bottom: 0em;
}

h4.date {
  margin-bottom: 2em;
}

/* 链接 */

a {
  color: blue;
}

/* 代码 */

code,
.md-fences {
  color: darkred;
  font-family: Courier;
  font-weight: bold;
}

div.sourceCode code {
  font-size: 14px;
  color: black;
  font-family: Consolas;
  font-weight: normal;
}

div.sourceCode code.sourceCode span.fu {
  color: #F75000;
}

div.sourceCode code.sourceCode span.sc {
  color: blue;
}

div.sourceCode code.sourceCode span.st {
  color: green;
}

div.sourceCode code.sourceCode span.co {
  color: grey;
}

div.sourceCode code.sourceCode span.dv {
  color: BlueViolet;
}

div.sourceCode code.sourceCode span.cn {
  color: darkcyan;
}

div.sourceCode code.sourceCode span.at {
  color: royalblue;
}

/* 粗体 */
strong {
  font-family: 'Microsoft YaHei';
}

/* 列表项 */

ul,
ol {
    margin: 0 0 1.5em 0.5em;
}

h3+ul,
h4+ul,
h5+ul,
h6+ul,
h3+ol,
h4+ol,
h5+ol,
h6+ol {
    margin-top: 0.5em;
}

p+ul,
p+ol {
    margin-top: 0.5em;
}

li>ul,
li>ol {
    margin-top: inherit;
    margin-bottom: 0;
    margin-left: 0.5em;
}

ul>li {
    list-style-type: disc;
    list-style-position: outside;
}

li ul>li {
    list-style-type: circle;
}

ol>li {
    list-style-type: decimal;
    list-style-position: outside;
}

li ol>li {
    list-style-type: upper-alpha;
}

li li ol>li {
    list-style-type: lower-greek;
}


/* 首行缩进 */

p {
    text-indent: 0em;
}


/* 表格 */
  
div.pagedtable{
  font-size:12px;
}

table {
    padding: 0;
    word-break: initial;
}

table tr {
    border-top: 1px solid #dfe2e5;
    margin: 0;
    padding: 0;
}

table tr:nth-child(2n),
thead {
    background-color: #fafafa;
}

table tr th {
    font-weight: bold;
    border: 1px solid #dfe2e5;
    border-bottom: 0;
    text-align: left;
    margin: 0;
    padding: 6px 13px;
}

table tr td {
    border: 1px solid #dfe2e5;
    text-align: left;
    margin: 0;
    padding: 6px 13px;
}

table tr th:first-child,
table tr td:first-child {
    margin-top: 0;
}

table tr th:last-child,
table tr td:last-child {
    margin-bottom: 0;
}


/* 侧边栏 */
div.col-lg-3 {
  width: 25%;
  max-width: 250px;
}

div.tocify {
  width: 20%;
  max-width: 200px;
  max-height: 90%;
  font-size: 16px;
}

div.toc-content {
  padding-left: 0px;
  padding-right: 40px;
}
```

```{r setup, include = FALSE}
## global options
knitr::opts_chunk$set(
  fig.width = 7,
  fig.asp = 0.618,
  out.width = "90%",
  fig.align = "center",
  fig.path = 'Figures/',
  fig.show = "hold",
  warn = 1,
  warning = FALSE,
  message = FALSE,
  echo = TRUE, # 是否显示代码
  eval = TRUE, # 是否运行代码块
  tidy = TRUE, # 代码排版
  comment = '>>>',
  collapse = F, # 代码与结果是否显示在同一代码块
  cache = T,
  cache.comments = F,
  autodep = TRUE
)

## use necessary packages
library('pacman')
p_load(
  # data processing
  tidyverse, lubridate, data.table, magrittr,
  # visualization
  ggthemes, showtext, gridExtra, r2d3, 
  # 可交互表格 DT::datatable()
  DT,
  # I/O 
  sqldf,
  # web crawler
  rvest, httr, reticulate
  )

## database engine
options(sqldf.driver = "SQLite")

# d3绘图的前景色和背景色
options(r2d3.theme = list(background = "white", foreground = "royalblack"))

## plotting
pdf.options(family = "GB1")
# 包含图的代码块需要fig.showtext = TRUE选项
showtext_auto(enable = TRUE)


## 自定义图形主题
# common template
mytheme <- theme_economist_white() +
  theme(
    text = element_text(family = 'YaHei'),
    plot.title = element_text(face = 'bold', size = 14),
    plot.subtitle = element_text(size = 12),
    plot.caption = element_text(
      hjust = 0,
      size = 10,
      margin = margin(2, 0, 0, 0, 'pt')
    ),
    plot.margin = margin(12, 10, 12, 0, 'pt'),
    legend.position = 'top',
    legend.justification = 'left',
    legend.margin = margin(4, 0, 0, 0, 'pt'),
    legend.key.size = unit(1, 'lines'),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10, margin = margin(0, 0, 0, 0, 'pt')),
    axis.text = element_text(size = 10, margin = margin(2, 0, 2, 0, 'pt')),
    axis.ticks.length = unit(-4, 'pt')
  )
# histogram template
theme_bar <- theme_economist_white() +
  theme(
    text = element_text(family = 'YaHei'),
    plot.title = element_text(face = 'bold', size = 14),
    plot.subtitle = element_text(size = 12),
    plot.caption = element_text(
      hjust = 0,
      size = 10,
      margin = margin(0, 0, 0, 0, 'pt')
    ),
    plot.margin = margin(12, 0, 12, 10, 'pt'),
    legend.position = 'top',
    legend.justification = 'left',
    legend.margin = margin(4, 0, 0, 0, 'pt'),
    legend.key.size = unit(0.7, 'lines'),
    legend.title = element_blank(),
    legend.text = element_text(size = 10, margin = margin(0, 8, 0, 4, 'pt')),
    axis.text = element_text(size = 10),
    axis.ticks.length = unit(0, 'pt') # 不要坐标轴须
  )
```



函数是一种功能的抽象。它有两个作用：`降低编程难度`和`代码复用`。

# 定义方式

## def 保留字

```python
def <函数名> (参数):
    '''
    函数的说明文档
    '''
    <函数体>
    return <返回值>
```

### 查看说明文档

`help(函数名)`或`print(函数名.__doc__)`

## lambda 保留字

`lambda <参数>: <作为返回值的表达式>`，lambda 语法的定义方式仅适用于一行内表示的函数，可以定义匿名函数

```python
f = lambda x, y: x + y
print(f(4,5))

def get_math_func(type) :
    '''
    该函数是一个函数加工厂，返回的是Lambda表达式
    '''
    if type == 'square':
        return lambda n: n * n
    elif type == 'cube':
        return lambda n: n * n * n
    else:
        return lambda n: (1 + n) * n / 2

# 调用get_math_func()，程序返回一个函数
math_func = get_math_func("cube")
print(math_func(5)) # 输出125
math_func = get_math_func("square")
print(math_func(5)) # 输出25
math_func = get_math_func("other")
print(math_func(5)) # 输出15.0
```
# 参数

## 必选参数

## 可选参数（有默认值的参数）

**函数定义时，必选参数在前，可选参数在后**，否则Python的解释器会报错。

可选参数降低了函数调用的难度，需要更复杂、更灵活的调用时，可以传递更多的参数来实现。从而无论是简单调用还是复杂调用，函数只需要定义一个。
```{python}
def power(x, n = 2):
    '''
    这是一个 n 次幂函数，默认求平方
    '''
    s = 1
    while n > 0:
        n = n - 1
        s = s * x
    return s

help(power)
power(5, 3)
power(5) 
```

### 可选参数必须指向不变对象

例1：
```{python}
def add_end(L = []): # []是可变对象
    '''
    L是一个指针，指向[]这个全局对象
    '''
    L.append('END')
    return L

add_end([1, 2, 3]) # L 指向了 [1, 2, 3]
add_end(['x', 'y', 'z']) # L 指向了 ['x', 'y', 'z']
add_end() # 若指向可变对象，如[]对象改变了，但 L 仍指向它的地址
add_end() # L 指向的是 ['END']，同样的执行会得到不同的结果
```

例2：
```{python}
def add_end(L = None): # None是不变对象
    if L is None:
        L = [] # []是函数内部声明的局部对象
    L.append('END')
    return L

add_end()
add_end()
```

## 可变参数

可变参数接受一个长度不确定的tuple，语法为`*参数名`。调用时使用逗号间隔或`*tuple`，才能被关键字参数识别

```{python}
def calc(*numbers):
    sum = 0
    for n in numbers:
        sum = sum + n * n
    return sum

calc(1, 3, 5, 7)
nums = (1, 3, 5, 7)
calc(*nums)
```

## 关键字参数

关键字参数接受一个可变长度的 dict, 调用时必须为逗号间隔的`key = value`形式，或`**dict`，才能被关键字参数识别

关键字参数可以扩展函数的功能。比如，在person函数里，我们保证能接收到name和age这两个参数，但是，如果调用者愿意提供更多的参数，我们也能收到。试想你正在做一个用户注册的功能，除了用户名和年龄是必填项外，其他都是可选项，利用关键字参数来定义这个函数就能满足注册的需求。

```{python}
def person(name, age, **kw):
    print('name:', name, 'age:', age, 'other:', kw)

person('Michael', 30)
person('Bob', 35, city='Beijing')
person('Adam', 45, gender='M', job='Engineer')

extra = {'city': 'Beijing', 'job': 'Engineer'}
person('Jack', 24, **extra)
```

## 命名关键字参数

目的：指定必须传入的关键字

语法：`*, 参数名`

命名关键字参数若没有默认值，被显式调用，调用时必须传入参数名，否则调用将报错：
```{python}
def person(name, age, *, city='Beijing', job): # 可以有默认值，city 和 job 都是命名关键字参数
    print(name, age, city, job)

person('Jack', 24, city='Beijing', job='Engineer')
# person('Jack', 24, 'Beijing', 'Engineer') 将报错
person('Jack', 24, job='Engineer') # 因 city 有默认值，可以隐式调用
```

如果函数定义中已经有了一个可变参数`*参数名`，后面跟着的命名关键字参数就不再需要一个特殊分隔符`*`了：

```{python}
def person(name, age, *args, city, job):
    '''
    city和job都是命名关键字参数
    '''
    print(name, age, args, city, job)

nums = (1, 3, 5, 7)
person('Jack', 24, *nums, city='Beijing', job='Engineer')
```

## 参数组合

5种参数都可以组合使用。但是请注意，为了提高程序的可读性，**参数定义的顺序应该是：必选参数、可选参数、可变参数、命名关键字参数和关键字参数**。

```{python}
def f1(a, b, c=0, *args, **kw):
    print('a =', a, 'b =', b, 'c =', c, 'args =', args, 'kw =', kw)

def f2(a, b, c=0, *, d, **kw):
    print('a =', a, 'b =', b, 'c =', c, 'd =', d, 'kw =', kw)

f1(1, 2)
f1(1, 2, c=3)
f1(1, 2, 3, 'a', 'b')
f1(1, 2, 3, 'a', 'b', x = 99)
f2(1, 2, d = 99, ext = None)

args = (1, 2, 3, 4)
kw = {'d': 99, 'x': '#'}
f1(*args, **kw)

args = (1, 2, 3)
kw = {'d': 88, 'x': '#'}
f2(*args, **kw)
```


## 函数的参数传递机制

一般来说，函数不能修改外部变量。因为传递给函数的是参数的副本，而非参数本身；但当参数为指针时，即使是副本，指向的也是同一个对象。

因此，**如果要让函数修改外部数据，可以通过把这些数据包装为列表、字典等可变对象，然后作为参数传递给函数，在函数内部用列表、字典的方法修改它们，这样才能改变这些数据**。

# 返回值

可以返回多个值，构成一个元组并省略括号

# 变量作用域

局部变量：函数内

全局变量：函数外

基本数据类型，可以用`global`声明在函数内部使用全局变量

列表、元祖等组合数据类型，只要不是函数内部创建的，默认调用同名全局变量，不需要`global`声明

# 函数式编程：作为对象的函数

`map(函数名，可遍历对象)`
```{python}
x = map(lambda x: x*x, range(8))
print(x, '\n', type(x),': ',[i for i in x])
```


