---
title: "5-1 Input-Output"
subtitle: ''
author: "Humoon"
date: "`r Sys.Date()`"
output:
  html_document: 
    code_download: true
    fig_caption: yes
    theme: united
    highlight: haddock
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  rticles::ctex:
    df_print: default
    fig_caption: yes
    number_sections: false
  word_document:
    fig_caption: yes
    toc: yes
    toc_depth: 3
    reference_docx: 
  pdf_document: 
    toc: yes
    toc_depth: 2
    latex_engine: xelatex
documentclass: ctexart
classoption: hyperref,
---

```{css, echo=FALSE}
/* 除了直接在Rmd中写css，还可以在 yaml 头部加入 css:"style.css" 来使用外部css文件 */
  
  
/* 全局 */

body {
    font-size: 16px;
    color: #333333;
    font-family: sans-serif, 'Segoe UI', Tahoma, Geneva, Verdana, SimSun;
}

p,
blockquote,
ul,
ol,
dl,
table {
    margin: 0.8em 0;
}


/* 多级标题 */

h1 {
    font-size: 32px;
    margin-top: 1em;
    margin-bottom: 1em;
    color: red;
    font-weight: bold;
}

h2 {
    font-size: 28px;
    margin-top: 1em;
    margin-bottom: 1em;
    color: purple;
    font-weight: bold;
}

h3 {
    color: darkslateblue;
    font-size: 24px;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    font-weight: bold;
}

h4 {
    font-size: 20px;
    font-weight: bold;
}

h1.title,
h3.subtitle,
h4.author,
h4.date {
    margin-top: 0.5em;
    margin-bottom: 0em;
}

h4.date {
  margin-bottom: 2em;
}

/* 链接 */

a {
  color: blue;
}

/* 代码 */

code,
.md-fences {
  color: darkred;
  font-family: Courier;
  font-weight: bold;
}

div.sourceCode code {
  font-size: 14px;
  color: black;
  font-family: Consolas;
  font-weight: normal;
}

div.sourceCode code.sourceCode span.fu {
  color: #F75000;
}

div.sourceCode code.sourceCode span.sc {
  color: blue;
}

div.sourceCode code.sourceCode span.st {
  color: green;
}

div.sourceCode code.sourceCode span.co {
  color: grey;
}

div.sourceCode code.sourceCode span.dv {
  color: BlueViolet;
}

div.sourceCode code.sourceCode span.cn {
  color: darkcyan;
}

div.sourceCode code.sourceCode span.at {
  color: royalblue;
}

/* 粗体 */
strong {
  font-family: 'Microsoft YaHei';
}

/* 列表项 */

ul,
ol {
    margin: 0 0 1.5em 0.5em;
}

h3+ul,
h4+ul,
h5+ul,
h6+ul,
h3+ol,
h4+ol,
h5+ol,
h6+ol {
    margin-top: 0.5em;
}

p+ul,
p+ol {
    margin-top: 0.5em;
}

li>ul,
li>ol {
    margin-top: inherit;
    margin-bottom: 0;
    margin-left: 0.5em;
}

ul>li {
    list-style-type: disc;
    list-style-position: outside;
}

li ul>li {
    list-style-type: circle;
}

ol>li {
    list-style-type: decimal;
    list-style-position: outside;
}

li ol>li {
    list-style-type: upper-alpha;
}

li li ol>li {
    list-style-type: lower-greek;
}


/* 首行缩进 */

p {
    text-indent: 0em;
}


/* 表格 */
  
div.pagedtable{
  font-size:12px;
}

table {
    padding: 0;
    word-break: initial;
}

table tr {
    border-top: 1px solid #dfe2e5;
    margin: 0;
    padding: 0;
}

table tr:nth-child(2n),
thead {
    background-color: #fafafa;
}

table tr th {
    font-weight: bold;
    border: 1px solid #dfe2e5;
    border-bottom: 0;
    text-align: left;
    margin: 0;
    padding: 6px 13px;
}

table tr td {
    border: 1px solid #dfe2e5;
    text-align: left;
    margin: 0;
    padding: 6px 13px;
}

table tr th:first-child,
table tr td:first-child {
    margin-top: 0;
}

table tr th:last-child,
table tr td:last-child {
    margin-bottom: 0;
}


/* 侧边栏 */
div.col-lg-3 {
  width: 25%;
  max-width: 250px;
}

div.tocify {
  width: 20%;
  max-width: 200px;
  max-height: 90%;
  font-size: 16px;
}

div.toc-content {
  padding-left: 0px;
  padding-right: 40px;
}
```

```{r setup, include = FALSE}
## global options
knitr::opts_chunk$set(
  fig.width = 7,
  fig.asp = 0.618,
  out.width = "90%",
  fig.align = "center",
  fig.path = 'Figures/',
  fig.show = "hold",
  warn = 1,
  warning = FALSE,
  message = FALSE,
  echo = TRUE, # 是否显示代码
  eval = TRUE, # 是否运行代码块
  tidy = TRUE, # 代码排版
  comment = '>>>',
  collapse = F, # 代码与结果是否显示在同一代码块
  cache = T,
  cache.comments = F,
  autodep = TRUE
)

## use necessary packages
library('pacman')
p_load(
  # data processing
  tidyverse, lubridate, data.table, magrittr,
  # visualization
  ggthemes, showtext, gridExtra, r2d3, 
  # 可交互表格 DT::datatable()
  DT,
  # I/O 
  sqldf,
  # web crawler
  rvest, httr, reticulate
  )

## database engine
options(sqldf.driver = "SQLite")

# d3绘图的前景色和背景色
options(r2d3.theme = list(background = "white", foreground = "royalblack"))

## plotting
pdf.options(family = "GB1")
# 包含图的代码块需要fig.showtext = TRUE选项
showtext_auto(enable = TRUE)


## 自定义图形主题
# common template
mytheme <- theme_economist_white() +
  theme(
    text = element_text(family = 'YaHei'),
    plot.title = element_text(face = 'bold', size = 14),
    plot.subtitle = element_text(size = 12),
    plot.caption = element_text(
      hjust = 0,
      size = 10,
      margin = margin(2, 0, 0, 0, 'pt')
    ),
    plot.margin = margin(12, 10, 12, 0, 'pt'),
    legend.position = 'top',
    legend.justification = 'left',
    legend.margin = margin(4, 0, 0, 0, 'pt'),
    legend.key.size = unit(1, 'lines'),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10, margin = margin(0, 0, 0, 0, 'pt')),
    axis.text = element_text(size = 10, margin = margin(2, 0, 2, 0, 'pt')),
    axis.ticks.length = unit(-4, 'pt')
  )
# histogram template
theme_bar <- theme_economist_white() +
  theme(
    text = element_text(family = 'YaHei'),
    plot.title = element_text(face = 'bold', size = 14),
    plot.subtitle = element_text(size = 12),
    plot.caption = element_text(
      hjust = 0,
      size = 10,
      margin = margin(0, 0, 0, 0, 'pt')
    ),
    plot.margin = margin(12, 0, 12, 10, 'pt'),
    legend.position = 'top',
    legend.justification = 'left',
    legend.margin = margin(4, 0, 0, 0, 'pt'),
    legend.key.size = unit(0.7, 'lines'),
    legend.title = element_blank(),
    legend.text = element_text(size = 10, margin = margin(0, 8, 0, 4, 'pt')),
    axis.text = element_text(size = 10),
    axis.ticks.length = unit(0, 'pt') # 不要坐标轴须
  )
```


# 控制台 I/O

`input()` 注意，其输入永远是字符串。如果需要用户输入整数，记得用`int(input())`转换一下，方便后续的使用。


`print()`


# 文件读写

## 文件是数据的抽象和集合

文件的展现方式：

- 文本形式，**使用单一特定编码**组成的文件，也被看成一个长字符串。如 `.txt`, `.py`, `.js`
- 二进制形式，直接由 0 和 1 组成，**没有统一的字符编码**。一般存在二进制 0 和 1 的组织结构，即文件格式。如 `.png`, `.avi`, `.docx`

Python 中读写文件的三个步骤：

- 打开文件：调用 `open(path)`，返回一个 File 对象
- 占用文件：调用 File 对象的 `.read()` 和 `.write()` 方法
- 关闭文件：调用 File 对象的 `.close()` 方法 

```
# 以文本形式打开并读取文件
tf = open('f.txt', 'rt') 
print(tf.readline())
tf.close()
```

```
# 以二进制形式打开并读取文件
bf = open('f.txt', 'rb') 
print(bf.readline())
bf.close()
```

## 打开文件

```
<变量名，又称文件句柄> = open(<文件路径/文件名>, <打开模式>)
```

打开模式|说明
--|--
'r'|只读，不存在返回 Error，**默认**
'x'|创建并写，文件已存在则返回 Error
'w'|覆盖写，不存在则创建，存在则覆盖
'a'|追加写，不存在则创建，存在则追加
'+'|用于 r/w/x/a 之后，在原功能基础上增加同时读写功能^[读的增加写，写的增加读。]
'b'|二进制
't'|文本文件模式，**默认**

## 关闭文件

```
<变量名，又称文件句柄>.close()
```

### 读写文件

函数|描述
--|--
<f>.read(size=-1)|默认读取全部。若给出参数，则读取前 size 长度
<f>.readline(size=-1)|默认读入一行。若给出参数，则读取前 size 长度
<f>.readlines(hint)|默认读入所有行，并**以每行为元素形成列表**。若给出参数，则读取前 hint 行。
<f>.write(s)|
<f>.writelines(lines)|将一个元素全部为字符串的列表写入文件，但并不会分行写，而是所有字符串直接拼接
<f>.seek(offset)|改变当前文件操作指针的位置。0:文件开头, 1:当前位置, 2:文件结尾。`f.seek(0)`，即回到文件开头。

```{python}
fo = open('ouput.txt', 'w+')
ls = ['中国', '法国', '美国']
fo.writelines(ls)
fo.seek(0) # 指针回到文件开头，才能遍历到写过的内容
for line in fo: # 其实就一行，没啥好遍历的
    print(line) 
fo.close()
```


### 处理大文件

- 一次读入，统一处理
```
fo = open(filename, 'r')
txt = fo.read()
fo.close()
```

- 少量读入，逐步处理
```
fo = open(filename, 'r')
txt = fo.read(2)
while txt != '':
    <对读入部分处理>
    txt = fo.read(2) # 读入一部分后，指针已经移动，再读是从指针所在位置继续往下读
fo.close()
```

- 一次读入，分行处理
```
fo = open(filename, 'r')
for line in fo.readlines():
  print(line)
fo.close()
```

- 分行读入，逐行处理
```
fo = open(filename, 'r')
for line in fo:
  print(line)
fo.close()
```

# 保存 Python 运行中产生的中间变量

## shelve 模块

可以用 shelve 模块将 Python 变量保存到二进制的 shelve 文件中，就像 R 语言中保存为 .Rdata 文件。

```{python}
import shelve

shelfFile = shelve.open('mydata')
cats = ['Zophie', 'Pooka', 'Simon']
shelfFile['cats'] = cats # shelve 对象就像一个字典
shelfFile.close()

shelfFile = shelve.open('mydata') 
type(shelfFile) 
shelfFile['cats']
shelfFile.close()

shelfFile = shelve.open('mydata')
list(shelfFile.keys()) # 查看 shelve 文件中储存着哪些数据
list(shelfFile.values())
shelfFile.close()
```

## 用 pprint.pformat() 保存字典

```{python}
import pprint
cats = [{'name': 'Zophie', 'desc': 'chubby'}, {'name': 'Pooka', 'desc': 'fluffy'}] 
pprint.pformat(cats)

fileObj = open('./myCats.py', 'w')
fileObj.write('cats = ' + pprint.pformat(cats) + '\n')
fileObj.close()
```

虽然没有直接储存字典数据类型，但通过将字符串保存在`.py`文件中，可以将该文件作为模块导入获得字典数据。<font color="red">这就像JavaScript中将对象保存为一个`.js`文件，也很方便调用。不同之处在于`.js`中引入的变量都是全局变量，可以直接使用变量名引用；而`.py`中引入的变量是局部的，要用`模块名.变量名`引用。</font>

```{python}
import myCats
print(myCats.cats)
```



